[package]
name = "sanny_builder_core"
version = "0.1.1"
authors = ["Seemann <mail@sannybuilder.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "core"
crate-type = ["rlib", "cdylib"]

[dependencies]
libc = "0.2.79"
nom = "6.0.1"
nom-recursive = "0.2.0"
nom_locate = {  git = "https://github.com/fflorent/nom_locate" }
