[package]
name = "gxt-parser"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gxt"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
byteorder = "1.5"
clap = { version = "4.5", features = ["derive"] }
crc32fast = "1.4"
encoding_rs = "0.8"

[dev-dependencies]
hex = "0.4"
